### ISSUE TITLE
documenting APIs

### ISSUE THREAD

**Issue by berli0z** [tracking-exposed/eu19#11]
We need to provide technical documentation for API usage, documenting the output of each one available. These is the checklist of (un-)documented APIs so far:

- [x] Personal Summary
- [x] Personal Stats
- [x] Personal Csv
- [x] Data Exporter
- [x] Delete your Data
- [x] General Statistics  
- [ ] Noogle
- [ ] Enrich
- [ ] semantics
- [ ] labels
- [ ] Loud
- [ ] langinfo
- [ ] languages
- [ ] keywords

**Comment by vecna** [comment]
the metadata should not be public, it is only accessible to help debug.

the summary and CSV they should be accessible in the personal page, for this: https://github.com/tracking-exposed/facebook/issues/115

**Comment by berli0z** [comment]
I'm breaking down the steps we need to take below:

- [ ] Test all the APIs [in this list](https://github.com/tracking-exposed/facebook/blob/8bd76eceeaecc66be8ceb6a3f40434bb364dd529/bin/content.js)
- [x] Choose a Framework (readthedocs.io)
- [ ] Make a full list of the working API (which will be the full reference)
- [ ] For each of them provide a list of information described below
- [ ] Describe format and Rate limits
- [ ] Write a FAQ

possible format for API info:
name - url - returned format - authentication type - rate limit, description of data for each parameter
 example request and response

**Comment by berli0z** [comment]
This is a potential format for APIs:

# API Docs

## Before you start
Lorem ipsum dolor sit amet etc.
Remember that URLs reference this values which are variables and can be obtained...
<br><br>`userToken`: is an unique<br>
`paging`: defines etc
## API Index
<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>URL</th>
  </tr>
  <tr>
    <td>Health Check</td>
    <td>[link]()</td>
    <td>/health</td>

  </tr>
  <tr>
    <td>Service Status</td>
    <td>[link]()</td>
    <td>/services</td>

  </tr>
  <tr>
    <td>RSS feed</td>
    <td>[link]()</td>
    <td>/feeds/query</td>

  </tr>
  <tr>
    <td>Personal Summary</td>
    <td>[link](#personalsummary)</td>
    <td>/personal/userToken/summary/paging</td>

  </tr>
  <tr>
    <td>Personal Summary Extended</td>
    <td>[link]()</td>
    <td>/personal/:userToken/extended/:paging?</td>

  </tr>
  <tr>
    <td>Personal Summary as CSV</td>
    <td>[link]()</td>
    <td>/personal/:userToken/csv/:dayrange?</td>

  </tr>
  <tr>
    <td>Semantics</td>
    <td>[link]()</td>
    <td>/personal/:userToken/semantics/:dayrange?</td>

  </tr>
  <tr>
    <td>Collective Stats</td>
    <td>[link]()</td>
    <td>/collective/:groupLabel/stats/:dayrange?</td>

  </tr>
  <tr>
    <td>Collective Summary</td>
    <td>[link]()</td>
    <td>/collective/:groupLabel/download/:dayrange?</td>

  </tr>
</table>


## <a name="personalsummary"></a>Personal Summary

#### URL
`https://facebook.tracking.exposed/api/personal/*:userToken*/summary/:paging`

#### Description
Returns a summary of personal data of an user based on its `userToken`. You can also specify `paging`. `userToken` is the token you get [here](#usertoken), and `paging` defines which range of data you will retrieve.

#### Data Specifics

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Format</th>
    <th>Example</th>
  </tr>
  <tr>
    <td>ID</td>
    <td>ID is an unique string that represents the single impression (which can be a post or a photo appeared on a specific timeline) </td>
    <td>string</td>
    <td>6769fd9f9ds6f0fddf</td>
  </tr>
  <tr>
    <td>publicationTime</td>
    <td>Time in which the specific post was published.</td>
    <td>date</td>
    <td>2019-01-01T11:41:00.000Z</td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td>bool</td>
    <td></td>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td>float64</td>
    <td></td>
  </tr>
  <tr>
    <td>Parameter</td>
    <td></td>
    <td>date</td>
    <td></td>
  </tr>
</table>

#### Sample Usage
Request:

    https://facebook.tracking.exposed/api/personal/0000f0f0f000f0000000/summary/1
Response:

    ```[{"_id":"0000f0f0f000f0000000","errors":[],"type":"posts","publicationTime":"1970-01-01T00:00:00.000Z","postId":"11111111111111111","permaLink":"/this.test/posts/10100100010101","author":"Test","authorLink":"https://www.facebook.com/test","texts":[],"textlength":0,"impressionTime":"2019-01-01T11:41:00.000Z","impressionOrder":1,"user":"insert-food-here","timeline":"insert-food-here"}]```

**Comment by berli0z** [comment]
New format here:
https://github.com/tracking-exposed/eu19/blob/master/texts-wip/api.md

**Comment by berli0z** [comment]
APIs documentation is done. small improvements will be made as minor bugs in production are fixed.

**Comment by berli0z** [comment]
Added new API personal/stats to the docs.
will also add

**Comment by vecna** [comment]
This is good as it is!
