### ISSUE TITLE
Rewriting individual.md

### ISSUE THREAD

**Issue by berli0z** [tracking-exposed/eu19#18]
We want to rewrite https://github.com/tracking-exposed/eu19/edit/master/content/page/individual.md
1. keeping in mind that is focused on self-assessment, so it is about "empowering individuals by getting access to fbtrex data"
2. as if eu19 would be published tomorrow

this means:
1. removing most of the text, putting it on another page or resuming it
2. inserting images to get an idea of how it would look like
3. completely rethinking the following:
> this data is then served up in a **webapp** as a persistent record of our own news feeds with menus to monitor our information diet in a visual and accessible manner, enabling us to rewind our news feeds and track personal trends, like what types of information we are consuming, which friends and networks influence us most, whether our interactions are fruitful, the amount of time we spend on Facebook, and then to compare this with friends.

the steps taken by an individual in order to get to know something about their information diet as of today are:
1. install the extension
2. use facebook
3. download data via csv (your data), via dashboard or via api
4. visualize it using different tools (excel, tableau, rawgraphs, python, R..)

i will include some pictures to get an idea of how it could look like. these could be short videos instead

**Comment by berli0z** [comment]
## install the extension
![image](https://user-images.githubusercontent.com/40333748/56972602-9101d580-6b6b-11e9-8135-245ade98f919.png)
## use facebook
![image](https://user-images.githubusercontent.com/40333748/56972905-243b0b00-6b6c-11e9-9eb4-d0d7faa598f1.png)
## download your data
![image](https://user-images.githubusercontent.com/40333748/56973061-68c6a680-6b6c-11e9-9f78-3651001d056b.png)
![image](https://user-images.githubusercontent.com/40333748/56973288-d70b6900-6b6c-11e9-8c45-528ac03cd79f.png)
+ link alla dash (install and usage) + link alla api
## visualize your data

**Comment by berli0z** [comment]
Opened a new separate file to work on, so we can compare the two options in the end.
https://github.com/tracking-exposed/eu19/edit/master/content/page/myDiet.md

other possible titles:
myInfo, myFbInfo, DietTracker, SocialHealth, fbInfo, Fitbook, knowyourself, knowyourhabits, healthmonitor, infodiet..

**Comment by berli0z** [comment]
![image](https://user-images.githubusercontent.com/40333748/57097644-8a649100-6d18-11e9-9ec5-777527d90ca0.png)

![image](https://user-images.githubusercontent.com/40333748/57097671-9f412480-6d18-11e9-8edd-ee027d4bceaf.png)

![image](https://user-images.githubusercontent.com/40333748/57097704-b3852180-6d18-11e9-84f1-590c59a17ba5.png)

**Comment by vecna** [comment]
:heart_eyes:

**Comment by berli0z** [comment]
![image](https://user-images.githubusercontent.com/40333748/57106209-18e30d80-6d2d-11e9-80fe-7a5c94f29ddc.png)

**Comment by vecna** [comment]
https://github.com/tracking-exposed/eu19/commit/74c6f2303e914d7683d302dfdba80d6b51e8266d

**Comment by berli0z** [comment]
Testing pics for new paragraph on "basic how to compare data between users":

![image](https://user-images.githubusercontent.com/40333748/57306578-5d7ef800-70e3-11e9-83b3-4e8fe59e4ff1.png)
![image](https://user-images.githubusercontent.com/40333748/57306586-62dc4280-70e3-11e9-974d-a7dcf0660275.png)

**Comment by berli0z** [comment]
- [] Adding links and alt text for the images in individual.md

**Comment by vecna** [comment]
thanks, it is in production
